# Site settings
title: Max Kruse
description: Die digitale Visitenkarte von Max Kruse
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: https://krumax.github.io

# User settings
username: Hallo! Ich bin <span class=highlight>Max Kruse</span>.
user_description: Nach meinem Studium der <b>Medieninformatik</b> an der <b>Technischen Universität Dresden</b> habe ich mir meine Sporen mit technischen Entwicklungsaufgaben im Plattformbereich über unterschiedliche Stationen bis hin zur <b>Agilen IT Projektleitung</b> verdient. Zu meinen Kunden gehörten DACH Energiekonzerne und Hersteller für Photovoltaik und Heimspeicheranlagen. Die <b>Digitalisierung der Energiewende</b> ist mir in den vergangenen Jahren ans Herz gewachsen. Ganz besonders das Spannungsfeld nachhaltiger IT im Zeitalter des Klimawandels reizt mich. Ich bin ein humorvoller, motivierter und technikbegeisterter Leader.
user_title: IT Projektleiter - Product Owner
email: xam.esurk@gmail.com
twitter_url: https://twitter.com/maxkruse
github_url:   https://github.com/krumax
instagram_url: https://www.instagram.com/xam_esurk
linkedin_url: www.linkedin.com/in/max-kruse-b7024a4b
stack_url: https://stackoverflow.com/users/1554767/xam-esurk
resume_url: https://krumax.github.io/assets/docs/resume.pdf

author: Max Kruse
street_address: Niederauer Staße 53
city: Dresden
zip_code: 01127
country: Deutschland


#About
about_title: Über mich

#Projects
projects_title: Projekte

# Technical Skills
technical-skills:
  title: Techische Fähigkeiten
  frontend_title: Frontend
  frontend: Javascript, AngularJS, HTML5, CSS, REST, TypeScript, grunt, npm
  backend_title: Backend
  backend: Node.js, PHP-Symphony, Swagger
  devops_title: DevOps
  devops: Docker, Grafana, Influx, Pingdom, Linux, Google Cloud Plattform
  qa_title: QA/Service
  qa: nightwatch.js, Jira Service Desk
  delivery_title: CI/CD
  delivery: Jenkins, Docker, Git, Bitbucket
  tooling_title: Tooling
  tooling: Jira, Confluence, Google Sheets, Controlling, Trello, Slack

# Product Skills
product-skills:
  title: Produkt Fähigkeiten
  agile_title: Agiles Mindset
  agile: Die Digitalisierung erfordert in der Zeit, in der wir arbeiten sowohl für Produkte, Projekte und Teams eine hohe und oft schwer kalkulierbare Beschleunigung. <b>Beschleunigung</b> ist jedoch nicht immer ein Indikator für hohe Geschwindigkeit. Daher ist es mir wichtig, die Teilhaber in den Prozessen auf die Chancen der <b>Iteration</b> vorzubereiten und zu begleiten. <b>Vertrauen</b>, <b>Offenheit</b>, <b>Einfachheit</b> fördern Fokus und die eigene Veränderbarkeit. Niemand ist ohne Fehler, kein Produkt ist ohne Fehler. Ein Team welches zur <b>Neugier</b> angespornt, offen mit Fehlern umgehen kann, sich weiterentwickeln will kann sehr viel mehr erreichen als in Pflichten- und Lastenheft orientierten Tätigkeiten. Eine stärkere Bindung zur eigenen Arbeit und Freiheitsgrade für Kunden sind einige Vorteile einer agilen Vorgehensweise.
  leadership_title: Teamführung
  leadership: Ich führe gern mit meiner <b>humorvollen</b> und <b>offenen</b> Art. Ein großer Antrieb meiner täglichen Arbeit ist, meine Kollegen, Mitmenschen und Freunde zu inspirieren. Jeder ist eine <b>starke Führungskraft</b>, der Menschen dazu befähigt selbst zu führen. Ich sehe ein Team nicht als Gruppe von Einzelkämpfern, sondern als das was mehr als die Summe seiner Einzelteile darstellt. Vertrauen, Ehrlichkeit, Kollegialität schafft einen immensen Zusammenhalt und eine <b>Team Integrität</b>, die sich in der täglichen Arbeit spürbar positiv auswirkt. Jeder sollte mit <b>Freude</b> seinen Arbeitsalltag beginnen und ebenso beenden.
  products_title: Produkte/Projekte
  products: Eine meiner wichtigsten Motivationen täglicher Arbeit ziehe ich aus einer starken <b>persönlichen Identifikation</b> mit Produkten oder Projekten. Es gibt im digitalen Umfeld kaum spannendere, reizvollere Abreitserfolge, als ein Produkt zu begleiten, es aus den Kinderschuhen zu helfen, es <b>stetig zu verbessern</b> oder neu auszurichten. Vor dem Hintergrund der Schnelllebigkeit unserer Zeit und der Halbwertszeit von Software stellen sich besondere Anforderungen an die tägliche Arbeit an Produkten. Ein tolles, motiviertes Team, ein agiles Mindset unterstützen die Arbeit daran ebenso stark wie eine geordnete, verständliche Sicht auf strategische Ausrichtung, Meilensteine, <b>Erfolge und Misserfolge</b>.

#Interests
interests:
  title: Interessen
  sport_title: Wassersport
  sport: Wellenreiten, Segeln, Windsurfen
  sustainability_title: Nachhaltigkeit
  sustainability: Themen zur Nachhaltigkeit, Erneuerbare Energien, Familie, Freunde
  beer_title: Bier
  beer: Das eigene Bier selber brauen - ein spannender und bekömmlicher Zeitvertreib
  music_movies_title: Film/Musik
  music_movies: Filme schauen und produzieren, Livemusik und Konserven konsumieren


# Milestones and Projects
projects:
  title: Meilensteine, Projekte und Tätigkeiten
  part-01:
    title: Platform Entwicklung
    date: Apr. 2012–Dez. 2014
    duration: 2 Jahre 9 Monate
    todos: Softwareentwicklung Frontend
    links:
      - uri: "https://www.kiwigrid.com/portfolio/the-independent-home-2"
        title: Kiwigrid GmbH
        description: Kiwigrid - The Independent Home
    description:
      - title: Softwareentwicklung Symfony 1.4
        description:  WebPortal Stack (PHP, JS, HTML) zur Visualisierung von Messwerten eines EnergyManagement/Homeautomation Gatewaysystems.
      - title: Softwareentwicklung Symfony 2.x
        description: Neuentwicklung WebApplikations Stack auf Basis von Symfony 2.x (PHP, JS, HTML) mit nahtloser Integration in eine Portallösung.
      - title: Softwareentwicklung WebApplication Stack angularJS
        description: Neuentwicklung eines Singlepage WebApp Stacks als Ersatz für PHP Portallösung auf Basis von angularJS
        details:
          - detail:
            description: Monitoring Stromflüsse, Bilanzen zu Eigenverbrauch, Selbstversorgung, Einspeisung und Netzbezug
          - detail:
            description: Export von Zeitreihen für Förderprogramme zur Subventionierung von Heimspeichern
          - detail:
            description: Integration von Heimspeicher, Photovoltaik, Digital Stromzähler Metriken
          - detail:
            description: Remote Gerätesteuerung, Eigenverbrauchsoptimierung, Zeitschaltuhren für SmartPlugs über eine einheitlich gestaltete WebApplikation
          - detail:
            description: Prognose von Zeitreihen zu Stromverbrauch/-erzeugung
  part-02:
    title: Technische Leitung
    date: Jan. 2015–Juni 2016
    duration: 1 Jahr 6 Monate
    todos: Architektur - Team Leitung - Technische Leitung - Softwareentwicklung
    description:
      - title: Technische Leitung
        description: Umsetzung, Planung von Frontend Software Projekten im Kundenkontext
        details:
          - detail:
            description: kundenbezogens, agiles Frontend Apps Entwicklungsteam
          - detail:
            description: Onboarding weiterer Mandanten für den WebApp Stack und kundenspezifische Weiterentwicklung (E.ON, enviaM)
          - detail:
            description: Migration WebApp Stack auf cloudbasierte Services (BigData Warehouse für Metriken, Userservices, Applicationservices, OAuth, REST, WebSockets) und Echtzeitkommunikation von Webfrontend zum EnergyManagement/Homeautomation Gateway
      - title: Softwareentwicklung
        description: Softwareentwicklung/-architektur im Frontendbereich JavaScript
        details:
          - detail:
            description: prototypischer Frontend für ShowCase SmartCharging mit Solarwatt und BMW für die CES 2015 in Las Vegas
          - detail:
            description: Integration weiterer gerätespezifischen WebApplikationen für Heimspeichergeneration Solarwatt MyReserve, MyReserve Matrix
          - detail:
            description: Migration WebApp Stack auf an neue cloudbasierte Services (u.a. Zeitserien, bidirektionale Echtzeitgerätekommunikation)
          - detail:
            description: Simulation von Eigenverbrauch-/Selbstversorgungsquoten zur Berechnung des Potentials von PV-Ausbau und/oder Integration von Heimspeicher mit Anbindung an Lead Generierung für den Kunden
  part-03:
    title: Projektleitung
    date: Juni 2016–Juli 2019
    duration: 3 Jahre 2 Monate
    todos: Architektur - Projektleitung - Produktentwicklung - Product Ownership
    links: 
      - uri: "https://www.solarwatt.de/energie-management"
        description: Energie Management Lösung der Solarwatt
        title: SOLARWATT Lösung
      - uri: "https://www.ekz.ch/de/private/strom-produzieren/eigenverbrauch.html"
        description: Eigenverbrauchsoptimierung der EKZ
        title: EKZ Lösung
    description:
      - title: Projektleitung
        description: Leitung zweier Kundenprojekte für die Kiwigrid (SOLARWATT und EKZ)
        details:
          - detail:
            description: Onboarding und Betreuung Elektrizitätswerke des Kanton Zürich; gemeinsame, agile Entwicklung einer Feature-Roadmap; Umsetzung von Meilensteinen; Qualitätssicherung; Feldtests; Dokumentationen
          - detail:
            description: Controlling, Projektplanung, Personalbeschaffung, Risikomanagement, Ressourcen- & Meilensteinplanung, Beratung, Angebotserstellung, Teamsteuerung, agile Projektabwicklung Time/Budget/Quality
      - title: Technische Leitung
        description: Technische Leitung, Ausrichtung und Steuerung eines Entwicklungsteams
        details:
          - detail:
            description: Integration weiterer Hardware/Frontend Schnittstellen für den Betrieb, Auswertung und Steuerung von&#58; neuester Generation SOLARWATT MyReserve Heimspeicher, MyStrom Smartplugs, keba P30 Ladesäulen (Treiberenwicklung auf JAVA Basis, Frontend angularJS)
          - detail:
            description: Migration Deployment/Build/Maintenance/Operations Stack in Google Cloud Platform, Unterstützung Softwarearchitektur, Unterstützung Build- und Deploymentprozesse, Qualitätssicherung und Releasemanagment (kubernetes, jenkins, ingress, helm)
      - title: Produktentwicklung
        description: Product Ownership für den gesamten kundenspezifischen Anforderungskatalog
        details:
          - detail:
            description: Eigenverbrauchoptimiertes Laden von unterschiedlichen elektrischen Fahrzeugen mit Hilfe eines EnergyManagement Gateway Systems und der keba P30 Ladesäule (Treiberentwicklung, Frontendentwicklung, Regelungssoftware), Heizstäbe, Smartplugs und SG Ready Wärmepumpen
          - detail:
            description: Lead Generierungs Tooling für PV Anlagen mit einem externen Entwicklungsteam modernsten Webtechnologien (Integration in Salesforce Backend, Verwendung WebComponents als Microfrontends)
      - title: Team Leitung
        description: 2 agile Scrum Teams (5-9 Personen)
  part-04:
    title: Produktentwicklung
    date: Juli 2019–November 2019
    duration: 5 Monate
    todos: Architektur - Release Manager - Product Ownership - Technische Leitung
    links:
      - uri: "https://www.kiwigrid.com/portfolio/the-independent-home-2"
        title: Kiwigrid GmbH
        description: Kiwigrid - The Independent Home
    description:
      - title: Produktentwicklung
        description: Featureiteration auf dem gesamten Stack für meine Kunden
        details:
          - detail:
            description: Integration OCPP in lokale, Gateway basierte Eigenverbrauchsoptimierung für den Betrieb von Ladesäulen und PV Anlagen (Residential; bis 10 kWp Anlagengröße)
          - detail:
            description: Unterstützung Migration Energy Management Stack in neue Gateway Plattform
      - title: Team Leitung
        description: 4 Personen Scrum Team

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
